# Generated by Django 4.2.13 on 2024-07-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantityInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unitPrice',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
